language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker

before_install:
  - docker build -t saikat180891/docker-angular .
script:
  - docker -d run saikat180891/docker-angular

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-angular"
  env: "DockerAngular-env"
  bucket_name: "elasticbeanstalk-us-east-2-744637309231"
  bucket_path: "docker-angular"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$SECRET_ACCESS_KEY"
