language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker

before_install:
  - npm install -g node-gyp
  - docker build -t saikat180891/docker-angular .
script:
  - docker run saikat180891/docker-angular
